@echo off
setlocal enabledelayedexpansion
title ACHME CRM - Database Auto Setup
color 0A

:: ================================================================
::  ACHME CRM - db.bat
::  Auto-creates the MySQL database, user, and ALL tables.
::  Just double-click (or right-click -> Run as Administrator).
::
::  Works with: MySQL 5.7, 8.0, 8.4, MySQL Workbench installs
:: ================================================================

net session >nul 2>&1
if errorlevel 1 (
    echo Requesting Administrator privileges...
    mshta vbscript:CreateObject("Shell.Application").ShellExecute("""%~f0""","","","runas",1)(window.close)
    exit /b 0
)

set "ROOT=%~dp0"
set "ROOT=%ROOT:~0,-1%"
set "BACKEND=%ROOT%\backend"
set "MYSQL_EXE="

cls
echo.
echo  ============================================================
echo    ACHME CRM ^|  DATABASE AUTO SETUP
echo    Creates: database, user, and all 40+ tables
echo  ============================================================
echo.

:: ============================================================
:: STEP 1 — Find mysql.exe
:: ============================================================
echo  [1/5] Locating MySQL...

:: Check if mysql is already in PATH
where mysql >nul 2>&1
if not errorlevel 1 (
    set "MYSQL_EXE=mysql"
    goto :found_mysql
)

:: Search all known MySQL install locations
for %%V in (8.4 8.3 8.2 8.1 8.0 5.7 5.6 9.0) do (
    if exist "C:\Program Files\MySQL\MySQL Server %%V\bin\mysql.exe" (
        set "MYSQL_EXE=C:\Program Files\MySQL\MySQL Server %%V\bin\mysql.exe"
        goto :found_mysql
    )
    if exist "C:\Program Files (x86)\MySQL\MySQL Server %%V\bin\mysql.exe" (
        set "MYSQL_EXE=C:\Program Files (x86)\MySQL\MySQL Server %%V\bin\mysql.exe"
        goto :found_mysql
    )
)

:: Other common locations
for %%P in (
    "C:\xampp\mysql\bin\mysql.exe"
    "C:\wamp\bin\mysql\mysql5.7.36\bin\mysql.exe"
    "C:\wamp64\bin\mysql\mysql8.0.31\bin\mysql.exe"
    "C:\laragon\bin\mysql\mysql-8.0\bin\mysql.exe"
    "C:\MySQL\bin\mysql.exe"
    "C:\mysql\bin\mysql.exe"
) do (
    if exist %%P (
        set "MYSQL_EXE=%%~P"
        goto :found_mysql
    )
)

:: Last resort — search Program Files
for /f "delims=" %%f in ('dir "C:\Program Files\MySQL\*.exe" /s /b 2^>nul ^| findstr /I "\\bin\\mysql.exe"') do (
    set "MYSQL_EXE=%%f"
    goto :found_mysql
)

:: Also try PATH additions for MySQL Workbench
set "PATH=%PATH%;C:\Program Files\MySQL\MySQL Shell 8.0\bin;C:\Program Files\MySQL\MySQL Server 8.0\bin"
where mysql >nul 2>&1
if not errorlevel 1 (
    set "MYSQL_EXE=mysql"
    goto :found_mysql
)

echo  [FAIL] mysql.exe not found on this machine.
echo.
echo  Please make sure MySQL is installed and add it to PATH:
echo    1. Open MySQL Installer from Start Menu
echo    2. Make sure "MySQL Server" is installed
echo    3. OR add C:\Program Files\MySQL\MySQL Server 8.0\bin to System PATH
echo.
pause
exit /b 1

:found_mysql
echo         Found: !MYSQL_EXE! [OK]

:: ============================================================
:: STEP 2 — Check MySQL service is running on port 3306
:: ============================================================
echo  [2/5] Starting MySQL service...
netstat -ano | findstr ":3306 " | findstr "LISTENING" >nul 2>&1
if not errorlevel 1 (
    echo         MySQL already running on port 3306. [OK]
    goto :mysql_running
)

echo         MySQL not running. Attempting to start...
for %%s in (MySQL84 MySQL80 MySQL MySQL57 MySQL56 mysql MariaDB) do (
    net start %%s >nul 2>&1
)
ping -n 6 127.0.0.1 >nul

netstat -ano | findstr ":3306 " | findstr "LISTENING" >nul 2>&1
if errorlevel 1 (
    echo.
    echo  [FAIL] MySQL is still not running on port 3306!
    echo         Open Services (services.msc) and start MySQL manually.
    pause
    exit /b 1
)
echo         MySQL started. [OK]

:mysql_running

:: ============================================================
:: STEP 3 — Connect as root and create DB + user
:: ============================================================
echo  [3/5] Creating database and user...
echo.

:: --- Write the SQL setup script to a temp file ---
set "SQL_FILE=%TEMP%\achme_setup.sql"

(
echo -- ACHME CRM Database Setup Script
echo -- Auto-generated by db.bat
echo.
echo -- Create database
echo CREATE DATABASE IF NOT EXISTS `achme`
echo   DEFAULT CHARACTER SET utf8mb4
echo   COLLATE utf8mb4_unicode_ci;
echo.
echo USE `achme`;
echo.
echo -- Create app user (both localhost and 127.0.0.1)
echo CREATE USER IF NOT EXISTS 'achme_user'@'localhost' IDENTIFIED BY 'AchmeSecure@2024';
echo CREATE USER IF NOT EXISTS 'achme_user'@'127.0.0.1' IDENTIFIED BY 'AchmeSecure@2024';
echo.
echo -- Grant full access to the achme database
echo GRANT ALL PRIVILEGES ON `achme`.* TO 'achme_user'@'localhost';
echo GRANT ALL PRIVILEGES ON `achme`.* TO 'achme_user'@'127.0.0.1';
echo.
echo -- Also grant root privileges to achme_user for safety
echo FLUSH PRIVILEGES;
echo.
echo -- ======================================================
echo -- CORE TABLES
echo -- ======================================================
echo.
echo CREATE TABLE IF NOT EXISTS `users` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `first_name` VARCHAR(100) NOT NULL,
echo   `last_name` VARCHAR(100) DEFAULT NULL,
echo   `email` VARCHAR(150) NOT NULL UNIQUE,
echo   `user_password` VARCHAR(255) NOT NULL,
echo   `role` ENUM('admin','user','manager') DEFAULT 'user',
echo   `status` ENUM('pending','active','rejected') DEFAULT 'pending',
echo   `mobile` VARCHAR(20) DEFAULT NULL,
echo   `emp_id` VARCHAR(50) DEFAULT NULL,
echo   `two_factor_enabled` TINYINT(1) DEFAULT 0,
echo   `profile_image` VARCHAR(255) DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `email_otp` (
echo   `email` CHAR(100) PRIMARY KEY,
echo   `otp` CHAR(6) DEFAULT NULL,
echo   `expires_at` DATETIME DEFAULT NULL
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `teammember` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `first_name` VARCHAR(100) DEFAULT NULL,
echo   `last_name` VARCHAR(100) DEFAULT NULL,
echo   `emp_email` VARCHAR(150) DEFAULT NULL,
echo   `mobile` VARCHAR(20) DEFAULT NULL,
echo   `mobile_number` VARCHAR(20) DEFAULT NULL,
echo   `job_title` VARCHAR(100) DEFAULT NULL,
echo   `emp_role` VARCHAR(50) DEFAULT NULL,
echo   `emp_id` VARCHAR(50) DEFAULT NULL,
echo   `user_id` INT DEFAULT NULL,
echo   `emp_address` TEXT DEFAULT NULL,
echo   `profile_image` VARCHAR(255) DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `telecalls` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `customer_name` VARCHAR(150) DEFAULT NULL,
echo   `mobile_number` VARCHAR(20) DEFAULT NULL,
echo   `email` VARCHAR(150) DEFAULT NULL,
echo   `location` VARCHAR(100) DEFAULT NULL,
echo   `reference` VARCHAR(255) DEFAULT NULL,
echo   `purpose` VARCHAR(255) DEFAULT NULL,
echo   `status` VARCHAR(50) DEFAULT 'New',
echo   `staff_name` VARCHAR(150) DEFAULT NULL,
echo   `notes` TEXT DEFAULT NULL,
echo   `created_by` INT DEFAULT NULL,
echo   `assigned_to` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `walkins` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `customer_name` VARCHAR(150) DEFAULT NULL,
echo   `mobile_number` VARCHAR(20) DEFAULT NULL,
echo   `email` VARCHAR(150) DEFAULT NULL,
echo   `location` VARCHAR(100) DEFAULT NULL,
echo   `reference` VARCHAR(255) DEFAULT NULL,
echo   `purpose` VARCHAR(255) DEFAULT NULL,
echo   `status` VARCHAR(50) DEFAULT 'New',
echo   `staff_name` VARCHAR(150) DEFAULT NULL,
echo   `notes` TEXT DEFAULT NULL,
echo   `created_by` INT DEFAULT NULL,
echo   `assigned_to` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `fields` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `customer_name` VARCHAR(150) DEFAULT NULL,
echo   `mobile_number` VARCHAR(20) DEFAULT NULL,
echo   `email` VARCHAR(150) DEFAULT NULL,
echo   `location` VARCHAR(100) DEFAULT NULL,
echo   `reference` VARCHAR(255) DEFAULT NULL,
echo   `purpose` VARCHAR(255) DEFAULT NULL,
echo   `status` VARCHAR(50) DEFAULT 'New',
echo   `staff_name` VARCHAR(150) DEFAULT NULL,
echo   `notes` TEXT DEFAULT NULL,
echo   `created_by` INT DEFAULT NULL,
echo   `assigned_to` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `customers` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `customer_name` VARCHAR(150) NOT NULL,
echo   `mobile_number` VARCHAR(20) DEFAULT NULL,
echo   `email` VARCHAR(150) DEFAULT NULL,
echo   `gst_number` VARCHAR(50) DEFAULT NULL,
echo   `location_city` VARCHAR(100) DEFAULT NULL,
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `clients` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `name` VARCHAR(150) NOT NULL,
echo   `company_name` VARCHAR(150) DEFAULT NULL,
echo   `email` VARCHAR(150) DEFAULT NULL,
echo   `phone` VARCHAR(20) DEFAULT NULL,
echo   `alternate_phone` VARCHAR(20) DEFAULT NULL,
echo   `address` TEXT DEFAULT NULL,
echo   `city` VARCHAR(100) DEFAULT NULL,
echo   `state` VARCHAR(100) DEFAULT NULL,
echo   `pincode` VARCHAR(20) DEFAULT NULL,
echo   `service` VARCHAR(255) DEFAULT NULL,
echo   `gst_number` VARCHAR(50) DEFAULT NULL,
echo   `notes` TEXT DEFAULT NULL,
echo   `client_status` ENUM('active','inactive','converted','prospect') DEFAULT 'active',
echo   `created_by` INT DEFAULT NULL,
echo   `assigned_teammember_id` INT DEFAULT NULL,
echo   `original_lead_id` INT DEFAULT NULL,
echo   `original_lead_type` ENUM('telecall','walkin','field') DEFAULT NULL,
echo   `converted_at` TIMESTAMP NULL DEFAULT NULL,
echo   `lead_email` VARCHAR(150) DEFAULT NULL,
echo   `lead_city` VARCHAR(100) DEFAULT NULL,
echo   `lead_reference` VARCHAR(255) DEFAULT NULL,
echo   `lead_purpose` VARCHAR(255) DEFAULT NULL,
echo   `lead_staff_name` VARCHAR(150) DEFAULT NULL,
echo   `lead_id_display` VARCHAR(50) DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `contracts` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `title` VARCHAR(200) DEFAULT NULL,
echo   `client_name` VARCHAR(150) DEFAULT NULL,
echo   `client_company` VARCHAR(200) DEFAULT NULL,
echo   `mobile_number` VARCHAR(20) DEFAULT NULL,
echo   `location_city` VARCHAR(100) DEFAULT NULL,
echo   `email` VARCHAR(150) DEFAULT NULL,
echo   `contract_type` VARCHAR(20) DEFAULT 'Service',
echo   `start_date` DATE DEFAULT NULL,
echo   `end_date` DATE DEFAULT NULL,
echo   `amount` DECIMAL(10,2) DEFAULT 0,
echo   `amount_value` DECIMAL(10,2) DEFAULT 0,
echo   `remaining` DECIMAL(10,2) DEFAULT 0,
echo   `status` VARCHAR(50) DEFAULT 'Active',
echo   `notes` TEXT DEFAULT NULL,
echo   `quotation_id` INT DEFAULT NULL,
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `tasks` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `task_title` VARCHAR(200) NOT NULL,
echo   `task_description` TEXT DEFAULT NULL,
echo   `assigned_to` VARCHAR(150) DEFAULT NULL,
echo   `assigned_teammember_id` INT DEFAULT NULL,
echo   `due_date` DATE DEFAULT NULL,
echo   `status` VARCHAR(50) DEFAULT 'Pending',
echo   `priority` VARCHAR(20) DEFAULT 'Normal',
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `quotations` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `customer_id` INT NOT NULL,
echo   `quotation_date` DATE NOT NULL,
echo   `reference_no` VARCHAR(50) DEFAULT NULL,
echo   `lead_id` INT DEFAULT NULL,
echo   `lead_type` VARCHAR(20) DEFAULT NULL,
echo   `subtotal` DECIMAL(12,2) DEFAULT 0,
echo   `total_tax` DECIMAL(12,2) DEFAULT 0,
echo   `total_discount` DECIMAL(12,2) DEFAULT 0,
echo   `grand_total` DECIMAL(12,2) DEFAULT 0,
echo   `total_cgst` DECIMAL(12,2) DEFAULT 0,
echo   `total_sgst` DECIMAL(12,2) DEFAULT 0,
echo   `total_igst` DECIMAL(12,2) DEFAULT 0,
echo   `from_address_id` INT DEFAULT NULL,
echo   `from_address_custom` TEXT DEFAULT NULL,
echo   `client_company` VARCHAR(150) DEFAULT NULL,
echo   `client_address1` TEXT DEFAULT NULL,
echo   `client_address2` TEXT DEFAULT NULL,
echo   `client_city` VARCHAR(100) DEFAULT NULL,
echo   `client_state` VARCHAR(100) DEFAULT NULL,
echo   `client_pincode` VARCHAR(20) DEFAULT NULL,
echo   `client_country` VARCHAR(50) DEFAULT 'India',
echo   `tax_type` VARCHAR(20) DEFAULT 'GST18',
echo   `custom_tax` VARCHAR(20) DEFAULT NULL,
echo   `gst_mode` VARCHAR(20) DEFAULT 'CGST_SGST',
echo   `exec_name` VARCHAR(100) DEFAULT NULL,
echo   `exec_phone` VARCHAR(20) DEFAULT NULL,
echo   `exec_email` VARCHAR(150) DEFAULT NULL,
echo   `terms_general` TINYINT(1) DEFAULT 0,
echo   `terms_tax` TINYINT(1) DEFAULT 0,
echo   `terms_project_period` VARCHAR(100) DEFAULT NULL,
echo   `terms_validity` VARCHAR(50) DEFAULT NULL,
echo   `terms_payment` VARCHAR(100) DEFAULT NULL,
echo   `terms_payment_custom` VARCHAR(100) DEFAULT NULL,
echo   `terms_warranty` VARCHAR(100) DEFAULT NULL,
echo   `hsn_sac_code` VARCHAR(50) DEFAULT NULL,
echo   `supplier_branch` VARCHAR(100) DEFAULT NULL,
echo   `bank_details_id` VARCHAR(50) DEFAULT NULL,
echo   `bank_company` VARCHAR(150) DEFAULT NULL,
echo   `bank_name` VARCHAR(100) DEFAULT NULL,
echo   `bank_account` VARCHAR(50) DEFAULT NULL,
echo   `bank_ifsc` VARCHAR(50) DEFAULT NULL,
echo   `bank_branch` VARCHAR(100) DEFAULT NULL,
echo   `custom_terms` TEXT DEFAULT NULL,
echo   `status` VARCHAR(20) DEFAULT 'Pending',
echo   `is_latest` TINYINT(1) DEFAULT 1,
echo   `parent_id` INT DEFAULT NULL,
echo   `version` INT DEFAULT 1,
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `quotation_items` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `quotation_id` INT NOT NULL,
echo   `product_number` INT NOT NULL,
echo   `description` VARCHAR(255) NOT NULL,
echo   `brand_model` VARCHAR(150) DEFAULT NULL,
echo   `hsn_sac` VARCHAR(20) DEFAULT NULL,
echo   `uom` VARCHAR(20) DEFAULT 'Nos',
echo   `price` DECIMAL(10,2) NOT NULL,
echo   `quantity` INT NOT NULL,
echo   `tax` DECIMAL(10,2) DEFAULT 0,
echo   `discount` DECIMAL(10,2) DEFAULT 0,
echo   `subtotal` DECIMAL(10,2) NOT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `call_reports` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `call_id` VARCHAR(20) DEFAULT NULL,
echo   `session_id` VARCHAR(50) DEFAULT NULL,
echo   `contract_id` INT DEFAULT NULL,
echo   `contract_title` VARCHAR(200) DEFAULT NULL,
echo   `service_type` ENUM('AMC','ALC','None') DEFAULT 'None',
echo   `client_name` VARCHAR(200) DEFAULT NULL,
echo   `customer_name` VARCHAR(200) DEFAULT NULL,
echo   `staff_name` VARCHAR(150) DEFAULT NULL,
echo   `executive_name` VARCHAR(150) DEFAULT NULL,
echo   `phone` VARCHAR(20) DEFAULT NULL,
echo   `mobile_number` VARCHAR(20) DEFAULT NULL,
echo   `location` VARCHAR(100) DEFAULT NULL,
echo   `location_city` VARCHAR(100) DEFAULT NULL,
echo   `call_sequence` INT DEFAULT 1,
echo   `report_date` DATE DEFAULT NULL,
echo   `start_time` TIME DEFAULT NULL,
echo   `end_time` TIME DEFAULT NULL,
echo   `assigned_time` INT DEFAULT 30,
echo   `actual_duration` INT DEFAULT 0,
echo   `is_exceeded` TINYINT(1) DEFAULT 0,
echo   `duration_limit` INT DEFAULT NULL,
echo   `complaint` TEXT,
echo   `description` TEXT,
echo   `remarks` TEXT,
echo   `petrol_charges` DECIMAL(10,2) DEFAULT 0,
echo   `spare_parts_price` DECIMAL(10,2) DEFAULT 0,
echo   `labour_charges` DECIMAL(10,2) DEFAULT 0,
echo   `total_expenses` DECIMAL(10,2) DEFAULT 0,
echo   `amount_collected` DECIMAL(10,2) DEFAULT 0,
echo   `payment_mode` VARCHAR(50) DEFAULT NULL,
echo   `payment_type` VARCHAR(50) DEFAULT NULL,
echo   `invoice_value` DECIMAL(10,2) DEFAULT 0,
echo   `payment_status` VARCHAR(50) DEFAULT NULL,
echo   `gst_number` VARCHAR(50) DEFAULT NULL,
echo   `company_name` VARCHAR(150) DEFAULT NULL,
echo   `status` ENUM('Pending','In Progress','Completed','Closed','Live','Observation') DEFAULT 'Completed',
echo   `priority` ENUM('Critical','High','Medium') DEFAULT 'Medium',
echo   `call_type` VARCHAR(50) DEFAULT 'AMC',
echo   `call_referrer` VARCHAR(150) DEFAULT NULL,
echo   `step2_completed` TINYINT(1) DEFAULT 0,
echo   `email` VARCHAR(150) DEFAULT NULL,
echo   `service_person` VARCHAR(150) DEFAULT NULL,
echo   `completed_at` TIMESTAMP NULL,
echo   `carry_forward_date` DATE NULL,
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `amc_alc_services` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `contract_id` INT NOT NULL,
echo   `contract_title` VARCHAR(150) DEFAULT NULL,
echo   `service_type` ENUM('AMC','ALC','None') DEFAULT 'AMC',
echo   `customer_name` VARCHAR(255) DEFAULT NULL,
echo   `mobile_number` VARCHAR(20) DEFAULT NULL,
echo   `location_city` VARCHAR(255) DEFAULT NULL,
echo   `service_date` DATE NOT NULL,
echo   `start_time` TIME DEFAULT NULL,
echo   `end_time` TIME DEFAULT NULL,
echo   `km` DECIMAL(10,2) DEFAULT NULL,
echo   `technician` VARCHAR(150) DEFAULT NULL,
echo   `sales_person` VARCHAR(150) DEFAULT NULL,
echo   `service_person` VARCHAR(255) DEFAULT NULL,
echo   `description` TEXT,
echo   `remarks` TEXT,
echo   `email` VARCHAR(150) DEFAULT NULL,
echo   `next_service_date` DATE DEFAULT NULL,
echo   `petrol_charges` DECIMAL(10,2) DEFAULT 0,
echo   `spare_parts_price` DECIMAL(10,2) DEFAULT 0,
echo   `labour_charges` DECIMAL(10,2) DEFAULT 0,
echo   `total_expenses` DECIMAL(10,2) DEFAULT 0,
echo   `amount_collected` DECIMAL(10,2) DEFAULT 0,
echo   `payment_mode` VARCHAR(50) DEFAULT NULL,
echo   `call_number` INT DEFAULT 1,
echo   `breakpoints` TEXT DEFAULT NULL,
echo   `duration_limit` INT DEFAULT NULL,
echo   `status` ENUM('Pending','In Progress','Completed') DEFAULT 'Completed',
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `notifications` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `task_id` INT NOT NULL DEFAULT 0,
echo   `user_id` INT DEFAULT NULL,
echo   `type` VARCHAR(50) DEFAULT NULL,
echo   `title` VARCHAR(150) DEFAULT NULL,
echo   `description` VARCHAR(255) DEFAULT NULL,
echo   `is_read` TINYINT DEFAULT 0,
echo   `is_archived` TINYINT(1) DEFAULT 0,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `admin_notifications` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `type` VARCHAR(50) DEFAULT 'registration',
echo   `user_id` INT DEFAULT NULL,
echo   `message` TEXT,
echo   `related_id` INT DEFAULT NULL,
echo   `related_type` VARCHAR(50) DEFAULT NULL,
echo   `created_by` INT DEFAULT NULL,
echo   `priority` VARCHAR(20) DEFAULT 'normal',
echo   `is_read` TINYINT(1) DEFAULT 0,
echo   `is_archived` TINYINT(1) DEFAULT 0,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `messages` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `sender_id` INT DEFAULT NULL,
echo   `receiver_id` INT DEFAULT NULL,
echo   `message` TEXT DEFAULT NULL,
echo   `type` VARCHAR(20) DEFAULT NULL,
echo   `seen` TINYINT(1) DEFAULT 0,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `payments` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `invoice_id` INT DEFAULT NULL,
echo   `amount` DECIMAL(10,2) NOT NULL,
echo   `payment_date` DATE NOT NULL,
echo   `payment_method` ENUM('Paypal','Cash','Bank') DEFAULT 'Cash',
echo   `Transaction_ID` INT DEFAULT NULL,
echo   `invoice_email` VARCHAR(150) DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `lead_reminders` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `lead_id` INT NOT NULL,
echo   `lead_type` ENUM('telecall','walkin','field') DEFAULT 'telecall',
echo   `reminder_date` DATE,
echo   `reminder_time` TIME DEFAULT NULL,
echo   `reminder_notes` TEXT,
echo   `status` ENUM('Pending','Done','Missed') DEFAULT 'Pending',
echo   `missed_count` INT DEFAULT 0,
echo   `notification_sent` TINYINT(1) DEFAULT 0,
echo   `employee_id` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `lead_activity` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `lead_id` INT NOT NULL,
echo   `lead_type` ENUM('telecall','walkin','field') DEFAULT 'telecall',
echo   `action` VARCHAR(100),
echo   `details` TEXT,
echo   `employee_id` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `lead_escalations` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `lead_id` INT NOT NULL,
echo   `lead_type` ENUM('telecall','walkin','field') DEFAULT 'telecall',
echo   `customer_name` VARCHAR(150),
echo   `mobile_number` VARCHAR(20),
echo   `staff_name` VARCHAR(150),
echo   `last_followup_date` DATE,
echo   `missed_count` INT DEFAULT 0,
echo   `missed_threshold_reached` TINYINT(1) DEFAULT 0,
echo   `employee_id` INT DEFAULT NULL,
echo   `status` ENUM('Open','Resolved') DEFAULT 'Open',
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `task_targets` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `user_id` INT DEFAULT NULL,
echo   `teammember_id` INT DEFAULT NULL,
echo   `user_name` VARCHAR(150) NOT NULL,
echo   `yearly_target` DECIMAL(15,2) DEFAULT 0,
echo   `monthly_target` DECIMAL(15,2) DEFAULT 0,
echo   `carry_forward` DECIMAL(15,2) DEFAULT 0,
echo   `effective_target` DECIMAL(15,2) DEFAULT 0,
echo   `created_by_admin` TINYINT(1) DEFAULT 1,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `task_achievements` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `user_id` INT DEFAULT NULL,
echo   `user_name` VARCHAR(150) NOT NULL,
echo   `target_id` INT NOT NULL,
echo   `month_year` VARCHAR(7) NOT NULL,
echo   `achieved_count` INT DEFAULT 0,
echo   `achieved_amount` DECIMAL(15,2) DEFAULT 0,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   UNIQUE KEY `unique_target_month` (`target_id`, `month_year`)
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `task_updates` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `user_id` INT DEFAULT NULL,
echo   `user_name` VARCHAR(150) NOT NULL,
echo   `target_id` INT NOT NULL,
echo   `month_year` VARCHAR(7) NOT NULL,
echo   `count` INT DEFAULT 0,
echo   `amount` DECIMAL(15,2) DEFAULT 0,
echo   `description` TEXT,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `task_assignments` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `task_id` INT,
echo   `assigned_to_user_id` INT,
echo   `assigned_to_user_name` VARCHAR(255),
echo   `assigned_by` VARCHAR(255),
echo   `status` ENUM('Pending','Accepted','Declined','In Progress','Completed') DEFAULT 'Pending',
echo   `assigned_date` DATE,
echo   `due_date` DATE,
echo   `priority` ENUM('Low','Normal','High','Urgent') DEFAULT 'Normal',
echo   `notes` TEXT,
echo   `response_notes` TEXT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `task_activity` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `task_id` INT,
echo   `action` VARCHAR(50),
echo   `message` TEXT,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `pi_from_addresses` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `label` VARCHAR(100) NOT NULL,
echo   `address` TEXT NOT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `performainvoices` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `customer_id` INT NOT NULL,
echo   `invoice_date` DATE NOT NULL,
echo   `reference_no` VARCHAR(50) DEFAULT NULL,
echo   `subtotal` DECIMAL(12,2) DEFAULT 0,
echo   `total_tax` DECIMAL(12,2) DEFAULT 0,
echo   `total_discount` DECIMAL(12,2) DEFAULT 0,
echo   `grand_total` DECIMAL(12,2) DEFAULT 0,
echo   `total_cgst` DECIMAL(12,2) DEFAULT 0,
echo   `total_sgst` DECIMAL(12,2) DEFAULT 0,
echo   `total_igst` DECIMAL(12,2) DEFAULT 0,
echo   `from_address_id` INT DEFAULT NULL,
echo   `from_address_custom` TEXT DEFAULT NULL,
echo   `client_company` VARCHAR(150) DEFAULT NULL,
echo   `client_address1` TEXT DEFAULT NULL,
echo   `client_city` VARCHAR(100) DEFAULT NULL,
echo   `client_state` VARCHAR(100) DEFAULT NULL,
echo   `client_pincode` VARCHAR(20) DEFAULT NULL,
echo   `client_country` VARCHAR(50) DEFAULT 'India',
echo   `tax_type` VARCHAR(20) DEFAULT 'GST18',
echo   `gst_mode` VARCHAR(20) DEFAULT 'CGST_SGST',
echo   `status` VARCHAR(20) DEFAULT 'Pending',
echo   `is_latest` TINYINT(1) DEFAULT 1,
echo   `parent_id` INT DEFAULT NULL,
echo   `version` INT DEFAULT 1,
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `performainvoice_items` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `invoice_id` INT NOT NULL,
echo   `product_number` INT NOT NULL,
echo   `description` VARCHAR(255) NOT NULL,
echo   `brand_model` VARCHAR(150) DEFAULT NULL,
echo   `hsn_sac` VARCHAR(20) DEFAULT NULL,
echo   `uom` VARCHAR(20) DEFAULT 'Nos',
echo   `price` DECIMAL(10,2) NOT NULL,
echo   `quantity` INT NOT NULL,
echo   `tax` DECIMAL(10,2) DEFAULT 0,
echo   `discount` DECIMAL(10,2) DEFAULT 0,
echo   `subtotal` DECIMAL(10,2) NOT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `estimate_invoices` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `customer_id` INT NOT NULL,
echo   `invoice_date` DATE NOT NULL,
echo   `reference_no` VARCHAR(50) DEFAULT NULL,
echo   `subtotal` DECIMAL(12,2) DEFAULT 0,
echo   `grand_total` DECIMAL(12,2) DEFAULT 0,
echo   `gst_mode` VARCHAR(20) DEFAULT 'CGST_SGST',
echo   `status` VARCHAR(20) DEFAULT 'Pending',
echo   `is_latest` TINYINT(1) DEFAULT 1,
echo   `parent_id` INT DEFAULT NULL,
echo   `version` INT DEFAULT 1,
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `estimate_invoice_items` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `invoice_id` INT NOT NULL,
echo   `product_number` INT NOT NULL,
echo   `description` VARCHAR(255) NOT NULL,
echo   `uom` VARCHAR(20) DEFAULT 'Nos',
echo   `price` DECIMAL(10,2) NOT NULL,
echo   `quantity` INT NOT NULL,
echo   `tax` DECIMAL(10,2) DEFAULT 0,
echo   `discount` DECIMAL(10,2) DEFAULT 0,
echo   `subtotal` DECIMAL(10,2) NOT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `service_estimations` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `customer_id` INT NOT NULL,
echo   `invoice_date` DATE NOT NULL,
echo   `reference_no` VARCHAR(50) DEFAULT NULL,
echo   `subtotal` DECIMAL(12,2) DEFAULT 0,
echo   `grand_total` DECIMAL(12,2) DEFAULT 0,
echo   `gst_mode` VARCHAR(20) DEFAULT 'CGST_SGST',
echo   `status` VARCHAR(20) DEFAULT 'Pending',
echo   `is_latest` TINYINT(1) DEFAULT 1,
echo   `parent_id` INT DEFAULT NULL,
echo   `version` INT DEFAULT 1,
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `services` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `client` VARCHAR(150) DEFAULT NULL,
echo   `material` VARCHAR(255) DEFAULT NULL,
echo   `warranty` VARCHAR(100) DEFAULT NULL,
echo   `amc` TINYINT(1) DEFAULT 0,
echo   `date` DATE DEFAULT NULL,
echo   `images` TEXT DEFAULT NULL,
echo   `issues` TEXT DEFAULT NULL,
echo   `gst_mode` VARCHAR(20) DEFAULT 'CGST_SGST',
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `clientinvoices` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `client_company` VARCHAR(150) DEFAULT NULL,
echo   `project_names` VARCHAR(150) DEFAULT NULL,
echo   `invoice_date` DATE DEFAULT NULL,
echo   `invoice_duedate` DATE DEFAULT NULL,
echo   `created_by` INT DEFAULT NULL,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `profile_change_requests` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `user_id` INT NOT NULL,
echo   `field` VARCHAR(50) NOT NULL,
echo   `new_value` TEXT,
echo   `status` ENUM('pending','approved','declined') DEFAULT 'pending',
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   `admin_response_at` TIMESTAMP NULL DEFAULT NULL
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `user_email_configs` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `user_id` INT NOT NULL,
echo   `email_user` VARCHAR(150) NOT NULL,
echo   `email_pass` VARCHAR(255) NOT NULL,
echo   `smtp_host` VARCHAR(100) DEFAULT 'smtp.gmail.com',
echo   `smtp_port` INT DEFAULT 587,
echo   `smtp_secure` VARCHAR(50) DEFAULT 'STARTTLS',
echo   `from_email_address` VARCHAR(150) DEFAULT NULL,
echo   `sender_name` VARCHAR(100) DEFAULT NULL,
echo   `provider` VARCHAR(50) DEFAULT NULL,
echo   `is_enabled` TINYINT(1) DEFAULT 1,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
echo   UNIQUE KEY `unique_user_id` (`user_id`)
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo CREATE TABLE IF NOT EXISTS `service_activity` (
echo   `id` INT AUTO_INCREMENT PRIMARY KEY,
echo   `service_id` INT,
echo   `activity_type` VARCHAR(50),
echo   `description` TEXT,
echo   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
echo ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
echo.
echo -- ======================================================
echo -- SEED DEFAULT ADMIN USER
echo -- Email: Kk@achmecommunication.com  Pass: kk@admin@123
echo -- ======================================================
echo INSERT IGNORE INTO `users`
echo   (first_name, last_name, email, user_password, role, status)
echo VALUES (
echo   'Admin', 'ACHME',
echo   'Kk@achmecommunication.com',
echo   '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
echo   'admin', 'active'
echo );
echo.
echo SELECT CONCAT('Setup complete! Tables created in database: ', DATABASE()) AS result;
) > "%SQL_FILE%"

:: --- Try to run SQL with different root passwords ---
set "DB_READY=0"

for %%P in ("" "root" "admin" "admin@123" "Root@123" "Admin@123" "mysql" "password" "12345678" "root123" "toor" "1234") do (
    if "!DB_READY!"=="0" (
        "!MYSQL_EXE!" -u root -p%%~P --host=127.0.0.1 --port=3306 --connect-timeout=5 < "%SQL_FILE%" >nul 2>&1
        if not errorlevel 1 (
            set "DB_READY=1"
            echo         Database created with root password: [%%~P or default] [OK]
        )
    )
)

:: --- If all auto attempts failed, ask user for root password ---
if "!DB_READY!"=="0" (
    echo.
    echo  MySQL root password not recognised automatically.
    echo  Please enter your MySQL root password:
    echo  (This is the password you set when installing MySQL/Workbench^)
    echo.
    set /p "ROOT_PASS=MySQL root password: "
    "!MYSQL_EXE!" -u root -p"!ROOT_PASS!" --host=127.0.0.1 --port=3306 < "%SQL_FILE%" >nul 2>&1
    if not errorlevel 1 (
        set "DB_READY=1"
        echo         Database created successfully. [OK]
    ) else (
        echo.
        echo  [FAIL] Still could not connect. Please check your MySQL root password.
        echo         OR open MySQL Workbench and manually run this SQL:
        echo         %SQL_FILE%
        echo.
        del "%SQL_FILE%" >nul 2>&1
        pause
        exit /b 1
    )
)

del "%SQL_FILE%" >nul 2>&1

:: ============================================================
:: STEP 4 — Write backend .env
:: ============================================================
echo  [4/5] Writing backend configuration...
(
echo PORT=5000
echo NODE_ENV=production
echo ALLOWED_ORIGIN=*
echo DEFAULT_TEST_PASSWORD=Test@12345
echo DB_HOST=127.0.0.1
echo DB_PORT=3306
echo DB_USER=achme_user
echo DB_PASS=AchmeSecure@2024
echo DB_NAME=achme
echo SMTP_HOST=smtp.gmail.com
echo SMTP_PORT=587
echo EMAIL_USER=thanan757@gmail.com
echo EMAIL_PASS=ghjv omqm hwji kerq
echo JWT_SECRET=97418d0c15d57ade768586b8501e35d34e5a5277f2a0570b6d5b47ef93f5b33e88b80045c60efd77e6edcbb015dbe46cf6747ce1dd8f11361f3e426ddc677c9a
) > "%BACKEND%\.env"
echo         backend/.env written. [OK]

:: ============================================================
:: STEP 5 — Run Node.js migrations (extra columns + seed)
:: ============================================================
echo  [5/5] Running Node.js setup for extra columns and seed data...
where node >nul 2>&1
if not errorlevel 1 (
    cd /d "%BACKEND%"
    if exist "%BACKEND%\node_modules" (
        call node ensure_db_user.js >nul 2>&1
        call node db_init.js >nul 2>&1
        echo         Node.js migration complete. [OK]
    ) else (
        echo         [WARN] node_modules not found. Run npm install in backend first.
    )
) else (
    echo         [WARN] Node.js not found - skipping migration step.
)

:: ============================================================
:: DONE
:: ============================================================
echo.
echo  ============================================================
echo   DATABASE SETUP COMPLETE!
echo.
echo   Database : achme
echo   User     : achme_user
echo   Password : AchmeSecure@2024
echo   Host     : 127.0.0.1:3306
echo.
echo   Admin Login to CRM:
echo     Email    : Kk@achmecommunication.com
echo     Password : kk@admin@123
echo.
echo   Next: Run start-servers.bat to launch the CRM.
echo  ============================================================
echo.
pause
exit /b 0
